--------------------------------------------------------
-- Archivo creado  - lunes-enero-17-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence IDAUTOR_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBAS"."IDAUTOR_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 17 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence IDLIBRO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PRUEBAS"."IDLIBRO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 20 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table TBL_AUTOR
--------------------------------------------------------

  CREATE TABLE "PRUEBAS"."TBL_AUTOR" 
   (	"ID_AUTOR" NUMBER, 
	"NOMBRECOMPLETO" VARCHAR2(50 BYTE), 
	"FECHANACIMIENTO" DATE, 
	"CIUDADPROCEDENCIA" VARCHAR2(100 BYTE), 
	"CORREO" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_LIBRO
--------------------------------------------------------

  CREATE TABLE "PRUEBAS"."TBL_LIBRO" 
   (	"ID_LIBRO" NUMBER, 
	"TITULO" VARCHAR2(100 BYTE), 
	"ANIO" VARCHAR2(100 BYTE), 
	"GENERO" VARCHAR2(100 BYTE), 
	"NUMEROPAGINAS" NUMBER, 
	"ID_AUTOR" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into PRUEBAS.TBL_AUTOR
SET DEFINE OFF;
Insert into PRUEBAS.TBL_AUTOR (ID_AUTOR,NOMBRECOMPLETO,FECHANACIMIENTO,CIUDADPROCEDENCIA,CORREO) values ('1','PRUEBA 1',to_date('16/01/22','DD/MM/RR'),'CALI','CARRERA@HOTMAIL.COM');
Insert into PRUEBAS.TBL_AUTOR (ID_AUTOR,NOMBRECOMPLETO,FECHANACIMIENTO,CIUDADPROCEDENCIA,CORREO) values ('2','PRUEBA 1',to_date('16/01/22','DD/MM/RR'),'CALI','CARRERA@HOTMAIL.COM');
Insert into PRUEBAS.TBL_AUTOR (ID_AUTOR,NOMBRECOMPLETO,FECHANACIMIENTO,CIUDADPROCEDENCIA,CORREO) values ('5','ALEX 3',to_date('16/10/22','DD/MM/RR'),'VALLE','VALLE@HOTMAIL.COM');
Insert into PRUEBAS.TBL_AUTOR (ID_AUTOR,NOMBRECOMPLETO,FECHANACIMIENTO,CIUDADPROCEDENCIA,CORREO) values ('10','cambio',to_date('02/10/12','DD/MM/RR'),'cali','сссссE@HOTMAIL.COM.CO');
Insert into PRUEBAS.TBL_AUTOR (ID_AUTOR,NOMBRECOMPLETO,FECHANACIMIENTO,CIUDADPROCEDENCIA,CORREO) values ('12','PRU vvvvvvv',to_date('02/10/12','DD/MM/RR'),'buga','kkkkkkkkkk@HOTMAIL.COM.CO');
Insert into PRUEBAS.TBL_AUTOR (ID_AUTOR,NOMBRECOMPLETO,FECHANACIMIENTO,CIUDADPROCEDENCIA,CORREO) values ('14','PRUEBA5555555555555',to_date('02/10/12','DD/MM/RR'),'cali','asasasssssssss@HOTMAIL.COM.CO');
Insert into PRUEBAS.TBL_AUTOR (ID_AUTOR,NOMBRECOMPLETO,FECHANACIMIENTO,CIUDADPROCEDENCIA,CORREO) values ('15','ffffff',to_date('02/10/93','DD/MM/RR'),'bogota','ffffffffff@HOTMAIL.COM.CO');
Insert into PRUEBAS.TBL_AUTOR (ID_AUTOR,NOMBRECOMPLETO,FECHANACIMIENTO,CIUDADPROCEDENCIA,CORREO) values ('16','PRUEBA OOOOO',to_date('02/10/12','DD/MM/RR'),'cali','сссссE@HOTMAIL.COM.CO');
REM INSERTING into PRUEBAS.TBL_LIBRO
SET DEFINE OFF;
Insert into PRUEBAS.TBL_LIBRO (ID_LIBRO,TITULO,ANIO,GENERO,NUMEROPAGINAS,ID_AUTOR) values ('2','aaaaaaaaaaaaaaaa','222','string','3','2');
Insert into PRUEBAS.TBL_LIBRO (ID_LIBRO,TITULO,ANIO,GENERO,NUMEROPAGINAS,ID_AUTOR) values ('11','jjjj','343','otro','123432','2');
Insert into PRUEBAS.TBL_LIBRO (ID_LIBRO,TITULO,ANIO,GENERO,NUMEROPAGINAS,ID_AUTOR) values ('16','ffffffffff','44444','hhhhh','233','5');
Insert into PRUEBAS.TBL_LIBRO (ID_LIBRO,TITULO,ANIO,GENERO,NUMEROPAGINAS,ID_AUTOR) values ('19','verde','1313','terror','244','5');
--------------------------------------------------------
--  DDL for Index TBL_AUTOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRUEBAS"."TBL_AUTOR_PK" ON "PRUEBAS"."TBL_AUTOR" ("ID_AUTOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_LIBRO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRUEBAS"."TBL_LIBRO_PK" ON "PRUEBAS"."TBL_LIBRO" ("ID_LIBRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger AL_INSERTA_AUTOR
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "PRUEBAS"."AL_INSERTA_AUTOR" before insert on TBL_Autor for each row
begin
    select IdAutor_seq.nextval into : new.Id_Autor from dual;
end;
/
ALTER TRIGGER "PRUEBAS"."AL_INSERTA_AUTOR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger AL_INSERTA_LIBRO
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "PRUEBAS"."AL_INSERTA_LIBRO" before insert on TBL_Libro for each row
begin
    select IdLibro_seq.nextval into : new.Id_Libro from dual;
end;
/
ALTER TRIGGER "PRUEBAS"."AL_INSERTA_LIBRO" ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_AUTOR
--------------------------------------------------------

  ALTER TABLE "PRUEBAS"."TBL_AUTOR" MODIFY ("ID_AUTOR" NOT NULL ENABLE);
  ALTER TABLE "PRUEBAS"."TBL_AUTOR" MODIFY ("NOMBRECOMPLETO" NOT NULL ENABLE);
  ALTER TABLE "PRUEBAS"."TBL_AUTOR" MODIFY ("FECHANACIMIENTO" NOT NULL ENABLE);
  ALTER TABLE "PRUEBAS"."TBL_AUTOR" MODIFY ("CIUDADPROCEDENCIA" NOT NULL ENABLE);
  ALTER TABLE "PRUEBAS"."TBL_AUTOR" MODIFY ("CORREO" NOT NULL ENABLE);
  ALTER TABLE "PRUEBAS"."TBL_AUTOR" ADD CONSTRAINT "TBL_AUTOR_PK" PRIMARY KEY ("ID_AUTOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_LIBRO
--------------------------------------------------------

  ALTER TABLE "PRUEBAS"."TBL_LIBRO" MODIFY ("TITULO" NOT NULL ENABLE);
  ALTER TABLE "PRUEBAS"."TBL_LIBRO" MODIFY ("ANIO" NOT NULL ENABLE);
  ALTER TABLE "PRUEBAS"."TBL_LIBRO" MODIFY ("GENERO" NOT NULL ENABLE);
  ALTER TABLE "PRUEBAS"."TBL_LIBRO" MODIFY ("NUMEROPAGINAS" NOT NULL ENABLE);
  ALTER TABLE "PRUEBAS"."TBL_LIBRO" ADD CONSTRAINT "TBL_LIBRO_PK" PRIMARY KEY ("ID_LIBRO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_LIBRO
--------------------------------------------------------

  ALTER TABLE "PRUEBAS"."TBL_LIBRO" ADD CONSTRAINT "FK_LIBROS_CODIGO" FOREIGN KEY ("ID_AUTOR")
	  REFERENCES "PRUEBAS"."TBL_AUTOR" ("ID_AUTOR") ENABLE;
